### ISSUE TITLE
Oops, we couldn't connect to "" when Maximizing/Restoring

### ISSUE THREAD

**Issue by jedatwork** [MicrosoftDocs/windowsserverdocs#1193]
I was experiencing this issue on a 4k monitor. Error details below

```[EmscriptenModule] 1 client.174e5906.js:1:27423
printErr
https://myrdweb/RDWeb/webclient/js/client.174e5906.js:1:27423
abort
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:133:13513
$2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
A$c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
Y1c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
___cxa_find_matching_catch
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3178356
___cxa_find_matching_catch_2
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3228116
_f
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:103:1
y2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vi
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271197
Yf
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:103:1
z2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271342
WUa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
Z2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viiii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3276298
en
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:122:1
U2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275495
ai
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:103:1
Z2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viiii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3276298
Yh
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:103:1
U2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275495
jWa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
rva
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:107:1
AZc
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
DZc
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
mWa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
nWa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
z7a
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:114:1
AZc
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
DZc
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
Gy
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:117:1
y2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
dynCall_vi_4496
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:4:12
runDestructor
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3184728
ClassHandle_delete
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3185101
A
https://myrdweb/RDWeb/webclient/js/client.174e5906.js:2:648
F
https://myrdweb/RDWeb/webclient/js/client.174e5906.js:2:4734
methodCaller_emscripten$$val_$emscripten$$val_emscripten$$val$
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:6:14
__emval_call_method
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3182711
aUa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
X2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_iiiii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275953
$Ta
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
U2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275495
NUa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
b8a
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:114:1
z2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271342
QUa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
z2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271342
IVa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
z2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vii
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271342
JVa
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
U2c
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
dynCall_viii_386
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:4:12
OnMessageCallback$Invoke
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:9:1
ASM_CONSTS</attachingObject.CreateMessageInvoker/<
https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:114036
uncaught exception: abort(1) at jsStackTrace@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:18017
stackTrace@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:18188
abort@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:133:13736
$2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
A$c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
Y1c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
___cxa_find_matching_catch@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3178356
___cxa_find_matching_catch_2@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3228116
_f@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:103:1
y2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vi@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271197
Yf@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:103:1
z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271342
WUa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
Z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3276298
en@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:122:1
U2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275495
ai@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:103:1
Z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3276298
Yh@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:103:1
U2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275495
jWa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
rva@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:107:1
AZc@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
DZc@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
mWa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
nWa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
z7a@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:114:1
AZc@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
DZc@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:125:1
Gy@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:117:1
y2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
dynCall_vi_4496@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:4:12
runDestructor@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3184728
ClassHandle_delete@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3185101
A@https://myrdweb/RDWeb/webclient/js/client.174e5906.js:2:648
F@https://myrdweb/RDWeb/webclient/js/client.174e5906.js:2:4734
methodCaller_emscripten$$val_$emscripten$$val_emscripten$$val$@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:6:14
__emval_call_method@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3182711
aUa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
X2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_iiiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275953
$Ta@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
U2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275495
NUa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
b8a@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:114:1
z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271342
QUa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271342
IVa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_vii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271342
JVa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
U2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
dynCall_viii_386@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:4:12
OnMessageCallback$Invoke@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:9:1
ASM_CONSTS</attachingObject.CreateMessageInvoker/<@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:114036

If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
2018-07-19T22:44:08.099Z Connection(ERR): The connection generated an internal exception with disconnect code=UnknownError(46), extended code=<null>, reason=Missing avc_on_decoded callback call?
 Thrown in thread 0 at:
    ../../ext-rd-protocol-s/lib/avccodec.cpp(141)
Call Stack:
        at $cb
        at Ycb
        at ufb
        at vUa
        at U2c
        at invoke_viii
        at NUa
        at a
        at y2c
        at invoke_vi
        at int
        at z2c
        at dynCall_vii_1198
        at HandleConnectionMessage�

    connection.cpp(1311): OnException() rdcore.6c727f31.js line 86 > Function:5:14
Core telemetry event: eventName=ConnectionException, traceMessage=An exception has occurred. Details: disconnect code=UnknownError(46), extended code=<null>, reason=Missing avc_on_decoded callback call?
 Thrown in thread 0 at:
    ../../ext-rd-protocol-s/lib/avccodec.cpp(141)
Call Stack:
        at $cb
        at Ycb
        at ufb
        at vUa
        at U2c
        at invoke_viii
        at NUa
        at a
        at y2c
        at invoke_vi
        at int
        at z2c
        at dynCall_vii_1198
        at HandleConnectionMessage�
client.174e5906.js:1:1185
The connection to wss://myrdweb/remoteDesktopGateway?CorId=%7B43cb1413-793f-484c-865c-e68bc72d0000%7D&ConId=%7B9e35a1b1-0b36-4c2f-91ac-43368717a052%7D&ClGen=HTML%3D1&ClBld=Type%3DRdClient%3B%20Build%3Dprivate&AuthS=SSPI_NTLM was interrupted while the page was loading. rdcore.6c727f31.js:86:26137
[SessionViewModel] Canvas lost focus client.174e5906.js:1:1070
[SessionViewModel] Resetting key state for: 86 client.174e5906.js:1:1070
[EmscriptenModule] 29 client.174e5906.js:1:27268
[EmscriptenModule] 29 client.174e5906.js:1:27423
uncaught exception: abort(29) at jsStackTrace@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:18017
stackTrace@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:18188
abort@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:133:13736
h4c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
X2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_iiiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275953
QSc@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:94:1
L2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viiiiiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3273815
GSc@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:94:1
A2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_iiiiiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3271514
RQc@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:94:1
E2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_iiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3272295
x4@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:115:1
Z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3276298
bUa@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:112:1
Z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3276298
QC@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:120:1
v2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viiiii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3270703
PC@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:120:1
U2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
invoke_viii@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:86:3275495
h7@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:115:1
X6@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:115:1
Z2c@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js:126:1
dynCall_viiii_146@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:4:12
IRdpInputController$SendKeycode@https://myrdweb/RDWeb/webclient/js/rdcore.6c727f31.js line 86 > Function:10:1
Connection/o.keyUp@https://myrdweb/RDWeb/webclient/js/client.174e5906.js:2:13248
Session/e.keyUp@https://myrdweb/RDWeb/webclient/js/client.174e5906.js:1:13387
SessionViewModel/k.canvasLostFocus/<@https://myrdweb/RDWeb/webclient/js/client.174e5906.js:4:18165

If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by lizap** [comment]
Sorry to hear that you've run into trouble. Unfortunately we don't have the resources to offer troubleshooting through the docs. Instead, your best option is to start a new thread on the [Remote Desktop clients forum](https://social.technet.microsoft.com/forums/windowsserver/en-us/home?forum=winrdc). Thanks!
