### ISSUE TITLE
Ajax error 400 when using RDP

### ISSUE THREAD

**Issue by h0rnman** [MicrosoftDocs/windowsserverdocs#1768]
Working with a secondary, untrusted domain, I am unable to connect to a servers via RDP.  I don't get an error, but it stays there and spins indefinitely.  Other tools appear to work fine, it appears that only the RDP tool is affected.
The machines I am attempting to connect to are a Windows Server 2012R2 Virtual Machine with WMF 5.1 (PSVersionTable reports 5.1.14409.1005), and a Windows Server 2016 (16.07 b14393.2551) Virtual Machine.  The machine running Windows Admin Center is a Server 2016 Virtual Machine (16.07 b14393.2551).

The WAC event logs show the following approximately 60 seconds after the first connection attempt (sanitized to remove my environment's server names):

sessionId : 1f2d287b-2e56-4f34-9142-c552a0ac622a
eventId : Trace
level : Error
sourceName : msft.sme.remote-desktop
source : appErrorHandler
timestamp : 1540313573444
message : ajax error 400
stack : Error: ajax error 400
   at t.prototype.error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1102705)
   at t.prototype._error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1101509)
   at t.prototype.error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1101180)
   at t.prototype._error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1101509)
   at t.prototype.error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1101180)
   at t.prototype.notifyError (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:2053362)
   at t.prototype._error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1590558)
   at t.prototype.error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1101180)
   at t.prototype._error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1101509)
   at t.prototype.error (https://server.corp.local/modules/msft.sme.remote-desktop/main.82adb1995258aa54b8d5.bundle.js:1:1101180)
moreEventData : 

The moreEventData tag is empty, that is the end of the record in the event log.

**Comment by RP-BE** [comment]
Exact same error here, but I can reproduce this also with machines inside the domain! 
In another environment this is working, but I cannot find the difference.

**Comment by IngridAtMicrosoft** [comment]
#please-close
