### ISSUE TITLE
ADFS 4.0 Add OpenLdap to ADFS requires Domain Admin

### ISSUE THREAD

**Issue by dbollaer** [MicrosoftDocs/windowsserverdocs#2745]
Hello,
I think your documentation should mention which type of role you need to execute these lines.
I first use system administrator, but for the Add-AdfsLocalClaimsProviderTrust -Name "Vendors" -Identifier "urn:vendors" -Type Ldap .... I needed Domain Administrator.

Here is a more detailed account from the actual error:

When I tried executing the final line:
```
Add-AdfsLocalClaimsProviderTrust ...
I got a strange error:
Add-AdfsLocalClaimsProviderTrust : The specified directory service attribute or value does not exist.
At line:1 char:1
+ Add-AdfsLocalClaimsProviderTrust –Name "ADLDS-ID-Store" –Identifier " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-AdfsLocalClaimsProviderTrust], COMException
    + FullyQualifiedErrorId : The specified directory service attribute or value does not exist.
,Microsoft.IdentityServer.Management.Commands.AddLocalClaimsProviderTrustCommand
```
When I try to get a more detailed error, I see this:

```
PS C:\Windows\system32&gt; $error[0]|Format-List * -Force

PSMessageDetails      :
Exception             : System.Management.Automation.ParameterBindingException: A parameter cannot be found that matche
                        s parameter name 'Identifier'.
                           at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(Par
                        ameterBindingException originalBindingException)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoV
                        alidation(Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Co
                        llection`1 arguments)
                           at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                           at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValue
                        s)
                           at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParamete
                        rValues)
                           at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                           at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Objec
                        t input)
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Objec
                        t input)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput
                        , CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirecti
                        on[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame fra
                        me)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
TargetObject          :
CategoryInfo          : InvalidArgument: (:) [Set-AdfsLocalClaimsProviderTrust], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.IdentityServer.Management.Commands.SetLocalClaimsProviderTrust
                        Command
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 1
PipelineIterationInfo : {}
```
After much searching I discovered that you need to use domain administrator.
Source:
https://social.technet.microsoft.com/Forums/ie/en-US/cdc4eddf-5f77-49bd-94af-2502b9a99c89/issue-adding-openldap-as-a-claims-provider-trust-in-adfs-40?forum=ADFS

After this I was able to add my openldap.
Full disclosure: I have not yet been able to login or with my openldap accounts.
The login option disappears, after I try to use it. I see no error.

So please add some additional documentation(references), on how to troubleshoot these types of issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6494d8-d525-8961-8dff-c5ee55a18849
* Version Independent ID: a3608a5f-26ed-1a93-2cd2-2fe2e5238248
* Content: [Configure AD FS to authenticate users stored in LDAP directories](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-to-authenticate-users-stored-in-ldap-directories)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
