### ISSUE TITLE
Cannot launch app, but can login

### ISSUE THREAD

**Issue by Condorello** [MicrosoftDocs/windowsserverdocs#3636]
I configured all without the use of the RD Gateway. I can access the workspace, but when i launch any app i receive a network broken error. Here the past of the rdweb client log, hope someone can help me:

`2019-12-15T16:39:21.454Z Exception: Possibly unhandled rejection: backdrop click Cause: undefined
at Object.Logger.a.error (https://win-2016.mydomain.com/rdweb/webclient/js/client.194eecb6.js:1:3067),at https://win-2016.mydomain.com/rdweb/webclient/js/client.194eecb6.js:5:6851,at j (https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:6:289),at n.$digest (https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:6:6299),at https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:6:8087,at Uc.b [as completeTask] (https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:6:14224),at https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:4:16482
2019-12-15T16:39:22.749Z RdpFileParser(NORM): Setting "redirectclipboard" = "1"
2019-12-15T16:39:22.749Z RdpFileParser(NORM): Setting "redirectprinters" = "1"
2019-12-15T16:39:22.750Z RdpFileParser(NORM): Setting "redirectcomports" = "1"
2019-12-15T16:39:22.750Z RdpFileParser(NORM): Setting "redirectsmartcards" = "1"
2019-12-15T16:39:22.750Z RdpFileParser(NORM): Setting "devicestoredirect" = "*"
2019-12-15T16:39:22.751Z RdpFileParser(NORM): Setting "drivestoredirect" = "*"
2019-12-15T16:39:22.751Z RdpFileParser(NORM): Setting "redirectdrives" = "1"
2019-12-15T16:39:22.751Z RdpFileParser(NORM): Setting "session bpp" = "32"
2019-12-15T16:39:22.752Z RdpFileParser(NORM): Setting "prompt for credentials on client" = "1"
2019-12-15T16:39:22.752Z RdpFileParser(NORM): Setting "span monitors" = "1"
2019-12-15T16:39:22.753Z RdpFileParser(NORM): Setting "use multimon" = "1"
2019-12-15T16:39:22.753Z RdpFileParser(NORM): Setting "remoteapplicationmode" = "1"
2019-12-15T16:39:22.753Z RdpFileParser(NORM): Setting "server port" = "3389"
2019-12-15T16:39:22.754Z RdpFileParser(NORM): Setting "allow font smoothing" = "1"
2019-12-15T16:39:22.754Z RdpFileParser(NORM): Setting "promptcredentialonce" = "0"
2019-12-15T16:39:22.754Z RdpFileParser(NORM): Setting "gatewayusagemethod" = "0"
2019-12-15T16:39:22.755Z RdpFileParser(NORM): Setting "gatewayprofileusagemethod" = "1"
2019-12-15T16:39:22.755Z RdpFileParser(NORM): Setting "gatewaycredentialssource" = "0"
2019-12-15T16:39:22.755Z RdpFileParser(NORM): Setting "full address" = "WIN-2016.mydomain.com"
2019-12-15T16:39:22.756Z RdpFileParser(NORM): Setting "alternate shell" = "||wordpad"
2019-12-15T16:39:22.756Z RdpFileParser(NORM): Setting "remoteapplicationprogram" = "||wordpad"
2019-12-15T16:39:22.756Z RdpFileParser(NORM): Setting "remoteapplicationname" = "WordPad"
2019-12-15T16:39:22.757Z RdpFileParser(NORM): Setting "remoteapplicationcmdline" = ""
2019-12-15T16:39:22.757Z RdpFileParser(NORM): Setting "workspace id" = "WIN-2016.mydomain.com"
2019-12-15T16:39:22.757Z RdpFileParser(NORM): Setting "use redirection server name" = "1"
2019-12-15T16:39:22.758Z RdpFileParser(NORM): Setting "loadbalanceinfo" = "tsv://MS Terminal Services Plugin.1.QuickSessionCollection"
2019-12-15T16:39:22.758Z RdpFileParser(NORM): Setting "alternate full address" = "WIN-2016.mydomain.com"
2019-12-15T16:39:22.758Z RdpFileParser(NORM): Setting "signscope" = "Full Address,Alternate Full Address,Use Redirection Server Name,Server Port,GatewayUsageMethod,GatewayProfileUsageMethod,GatewayCredentialsSource,PromptCredentialOnce,Alternate Shell,RemoteApplicationProgram,RemoteApplicationMode,RemoteApplicationName,RemoteApplicationCmdLine,RedirectDrives,RedirectPrinters,RedirectCOMPorts,RedirectSmartCards,RedirectClipboard,DevicesToRedirect,DrivesToRedirect,LoadBalanceInfo"
2019-12-15T16:39:22.759Z RdpFileParser(NORM): Setting "signature" BLABLABLA  GUl39DBA5GunR7+m8MTE3YvccP4=  "
2019-12-15T16:39:22.762Z [SessionFactory] Redirections request
2019-12-15T16:39:24.308Z [ConnectionFactory] Creating connection to: 
2019-12-15T16:39:24.309Z [object Object]
2019-12-15T16:39:24.404Z RdClientConnectionProxy::Create(NORM): loading webworkers from path: https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js
2019-12-15T16:39:24.419Z WebWorker(NORM): Created Webworker with path: https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js onMessage: HandleConnectionMessage
2019-12-15T16:39:24.436Z [SessionProvider] Connection created event received.
2019-12-15T16:39:24.436Z [SessionFactory] Launching remote app: ||wordpad
2019-12-15T16:39:24.436Z [Connection] Rail is not active adding application to pending list: ||wordpad
2019-12-15T16:39:24.436Z [SessionProvider] Session created received in provider
2019-12-15T16:39:24.436Z [SessionViewModel] Session created event received for: c301e83a-ee8d-46af-9312-4106b05a5492
2019-12-15T16:39:24.436Z [Connection] Connection.connect called
2019-12-15T16:39:24.436Z [SessionViewModel] Received monitorBound event on UI layer
2019-12-15T16:39:24.442Z [Session] Session focus changed to true id:c301e83a-ee8d-46af-9312-4106b05a5492 window id:null
2019-12-15T16:39:24.442Z [SessionViewModel] Session focused event received in view model session id: c301e83a-ee8d-46af-9312-4106b05a5492
2019-12-15T16:39:30.123Z Connection(NORM): Connection created with correlation ID={6a5125ce-c4d0-42c5-a274-245a5f7d0000}
2019-12-15T16:39:30.459Z DVCManager(NORM): Registered plugin DisplayControlGraphicsPlugin
2019-12-15T16:39:30.467Z DVCManager(NORM): Registered plugin InputPlugin
2019-12-15T16:39:30.519Z DVCManager(NORM): Registered plugin GfxChannelGraphicsPlugin
2019-12-15T16:39:31.182Z Connection(NORM): Using WebSocket Protocol wss
2019-12-15T16:39:31.236Z DVCManager(NORM): Creating plugin DisplayControlGraphicsPlugin
2019-12-15T16:39:31.264Z DVCManager(NORM): Registering a listener for DVC Microsoft::Windows::RDS::DisplayControl
2019-12-15T16:39:31.267Z DVCManager(NORM): Creating plugin GfxChannelGraphicsPlugin
2019-12-15T16:39:31.487Z DVCManager(NORM): Registering a listener for DVC Microsoft::Windows::RDS::Graphics
2019-12-15T16:39:31.521Z DVCManager(NORM): Creating plugin InputPlugin
2019-12-15T16:39:31.545Z DVCManager(NORM): Registering a listener for DVC Microsoft::Windows::RDS::Input
2019-12-15T16:39:31.564Z WebSocketTransport(NORM): Connection process begun for url=wss://WIN-2016.mydomain.com:3392/rdp
2019-12-15T16:39:31.572Z [Connection] Connection state changed to: Opening remote port
2019-12-15T16:39:31.572Z [SessionViewModel] Session c301e83a-ee8d-46af-9312-4106b05a5492 changed canvas display to none
2019-12-15T16:39:31.632Z WebSocketTransport(ERR): WebSocket error received for url=wss://WIN-2016.mydomain.com:3392/rdp
    websockettransport.cpp(304): OnErrorFromJS()
at Object.Logger.a.errorWithoutTimestamp (https://win-2016.mydomain.com/rdweb/webclient/js/client.194eecb6.js:1:2855),at Function.<anonymous> (https://win-2016.mydomain.com/rdweb/webclient/js/client.194eecb6.js:5:7952),at methodCaller_emscripten$$val_$emscripten$$val_emscripten$$val$ (eval at new_ (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1499616), <anonymous>:6:26),at __emval_call_method (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1521150),at I$a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:713702),at ujd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283347),at invoke_viiiii (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1572907),at H$a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:712115),at sjd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283181),at invoke_viii (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1572497),at x0a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:751280),at Hfb (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:97:365174),at qjd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283050),at invoke_vii (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1572108),at s1a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:788476),at qjd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283050),at invoke_vii (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1572108),at t1a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:789288),at sjd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283181),at dynCall_viii_471 (eval at makeDynCaller (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:1:1), <anonymous>:4:12),at OnMessageCallback$Invoke [as Invoke] (eval at new_ (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1499616), <anonymous>:9:1),at Worker.<anonymous> (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:106254)
2019-12-15T16:39:31.667Z WebSocketTransport(NORM): WebSocket closed, url=wss://WIN-2016.mydomain.com:3392/rdp, wasClean=false, code=1006, reason=""
2019-12-15T16:39:31.914Z Connection(ERR): The connection generated an internal exception with disconnect code=ConnectionBroken(8), extended code=<null>, reason=WebSocket closed with code: 1006 reason: 
 Thrown in thread 399776 at:
    websockettransport.cpp(330)
Call Stack:
        at _lb
        at Xlb
        at Tp
        at ujd#

    connection.cpp(1333): OnException()
at Object.Logger.a.errorWithoutTimestamp (https://win-2016.mydomain.com/rdweb/webclient/js/client.194eecb6.js:1:2855),at Function.<anonymous> (https://win-2016.mydomain.com/rdweb/webclient/js/client.194eecb6.js:5:7952),at methodCaller_emscripten$$val_$emscripten$$val_emscripten$$val$ (eval at new_ (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1499616), <anonymous>:6:26),at __emval_call_method (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1521150),at I$a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:713702),at ujd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283347),at invoke_viiiii (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1572907),at H$a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:712115),at sjd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283181),at invoke_viii (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1572497),at x0a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:751280),at Hfb (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:97:365174),at qjd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283050),at invoke_vii (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1572108),at s1a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:788476),at qjd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283050),at invoke_vii (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1572108),at t1a (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:95:789288),at sjd (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:99:283181),at dynCall_viii_471 (eval at makeDynCaller (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:1:1), <anonymous>:4:12),at OnMessageCallback$Invoke [as Invoke] (eval at new_ (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:1499616), <anonymous>:9:1),at Worker.<anonymous> (https://win-2016.mydomain.com/rdweb/webclient/js/rdcore.2d28f0f1.js:86:106254)
2019-12-15T16:39:31.975Z [Connection] Disconnecting
2019-12-15T16:39:32.011Z WebSocketTransport(NORM): Connection close initiated for url=wss://WIN-2016.mydomain.com:3392/rdp, code=1000, reason="NormalClosure(1000)"
2019-12-15T16:39:32.018Z [Connection] Disconnected
2019-12-15T16:39:32.018Z [SessionViewModel] Received retireCanvas event on UI layer, connectionID=6a5125ce-c4d0-42c5-a274-245a5f7d0000
2019-12-15T16:39:32.018Z [SessionProvider] Session disconnect received in provider
2019-12-15T16:39:32.018Z [SessionViewModel] Received didDisconnect event on UI layer
2019-12-15T16:39:32.021Z [Connection] Cleaning up connection
2019-12-15T16:39:32.021Z [SessionProvider] Connection destroyed event received.
2019-12-15T16:39:32.021Z [SessionProvider] Session disconnect received in provider
2019-12-15T16:39:32.021Z [SessionViewModel] Received didDisconnect event on UI layer
2019-12-15T16:39:32.021Z WebWorker(NORM): Destroying Webworker
2019-12-15T16:39:32.054Z [SessionViewModel] Canvas lost focus
2019-12-15T16:39:37.119Z Exception: Possibly unhandled rejection: backdrop click Cause: undefined
at Object.Logger.a.error (https://win-2016.mydomain.com/rdweb/webclient/js/client.194eecb6.js:1:3067),at https://win-2016.mydomain.com/rdweb/webclient/js/client.194eecb6.js:5:6851,at j (https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:6:289),at n.$digest (https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:6:6299),at https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:6:8087,at Uc.b [as completeTask] (https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:6:14224),at https://win-2016.mydomain.com/rdweb/webclient/js/components.35fcac4e.js:4:16482
`

**Comment by fofoseb** [comment]
Hi Condorello
Have you solved it?
I've the same issue without any causes.
All the rdp services works well but the webclient has wrong connection at startup

**Comment by Condorello** [comment]
Hi, i'm on Win2016 and i discovered that rd gateway is a requiments for make it working. You can bypass the usage of RD Gateway ONLY on win 2019. After i installed RD Gateway role i republished the remoteapp group and all is working!
