### ISSUE TITLE
ADFS  RapidrecreationTool restore error

### ISSUE THREAD

**Issue by gashme** [MicrosoftDocs/windowsserverdocs#4468]
Hi there, 
I Need help with the ADFSRapidrecreationtool.

i receive the following error  when try to restore an AD FS V4 farm with ADFSRapidRecreationTool (i've used this tool a lot of  time without problem before)

error:
restore-ADFS : Key not valid for use in specified state

The trace log files referred to the following event: 
Failed to update certificate permissions.

i've also checked that the Adfs service account and the adfssrv local account  have the correct permissions to the private key for my certificates

Below, the last lines of trace file:
[15:29:36] [INFO] Microsoft.IdentityServer.Deployment.Core.Result{Context=DeploymentSucceeded,Message=The configuration completed successfully.}
[15:29:36] [INFO] Attempting to grant access to the following key User NT Service\adfssrv : storeName My : storeLocation LocalMachine : cert thumbprint xxxxxxxxxxxxxxxxxxxxxxxxxxx
[15:29:36] [INFO] Detected security key format CNG
[15:29:36] [ERROR] Failed to update certificate permissions
[15:29:36] [ERROR] System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.NCryptNative.GetProperty(SafeNCryptHandle ncryptObject, String propertyName, CngPropertyOptions propertyOptions, Boolean& foundProperty)
   at System.Security.Cryptography.CngKey.GetProperty(String name, CngPropertyOptions options)
   at Microsoft.ADFSRapidRecreationTool.Crypto.X509KeyManagement.AddAclCngKey(Logger log, X509Certificate2 certificate, CryptoKeyAccessRule ACL)
   at Microsoft.ADFSRapidRecreationTool.Crypto.X509KeyManagement.GrantPrivateKeyPermissions(Logger log, StoreName storeName, StoreLocation storeLocation, String certThumbprint, String account)

Someone have already see this error ?
any solution ?
Thanks a lot for your help

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual error reports, improvement suggestions and update requests for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by Xelu86** [comment]
Hey gashme,

Thanks for contacting Microsoft. We value your feedback.

As we understand it, you've described an issue with a Windows product or service, rather than the documentation itself.

GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
