### ISSUE TITLE
SMS fails at the "Specify the destination for" step

### ISSUE THREAD

**Issue by cbuit** [MicrosoftDocs/windowsserverdocs#5176]
Below I have pasted the log output for this issue. The operation fails when 'Specify the destination for' scan is initiated.

01/07/2021-09:30:21.051 [Info] GetDeviceSmbEndpoints request job=UserFolderMigration deviceName=cob-fs01.cityofbuda.local maxCount=100 token=    [d:\os\src\base\dms\service\StorageMigrationService.IInventory.cs::GetDeviceSmbEndpoints::865]
01/07/2021-09:30:21.270 [Info] GetTransferDevicePairs request job=UserFolderMigration maxCount=100 token=    [d:\os\src\base\dms\service\StorageMigrationService.ITransfer.cs::GetTransferDevicePairs::816]
01/07/2021-09:30:21.395 [Info] SetTransferDevicePair request job=UserFolderMigration source=cob-fs01.cityofbuda.local destination=COB-FS-01    [d:\os\src\base\dms\service\StorageMigrationService.ITransfer.cs::SetTransferDevicePair::572]
01/07/2021-09:30:21.426 [Info] Skipping RegisterDestinationProxy for localhost for COB-FS-01.CityOfBuda.local    [d:\os\src\base\dms\service\SmsUtil.cs::RegisterDestinationProxy::2470]
01/07/2021-09:30:21.473 [Info] GetOsVersion(COB-FS-01.CityOfBuda.local)    [d:\os\src\base\dms\common\CimSessionHelper.cs::GetOsVersion::65]
01/07/2021-09:30:21.473 [Info] Computer 'COB-FS-01.CityOfBuda.local': OS version 10.0    [d:\os\src\base\dms\common\CimSessionHelper.cs::GetOsVersion::79]
01/07/2021-09:30:21.581 [Info] GetSafeClusterHandleQuick(COB-FS-01.CityOfBuda.local)    [d:\os\src\base\dms\common\FCFramework\ClusterUtils.cs::GetSafeClusterHandleQuick::2239]
01/07/2021-09:30:22.896 [Info] GetClusterNodesWhenClustered() could not get cluster nodes due to 'FailoverCluster feature is not installed on 'COB-FS-01.CityOfBuda.local''. Error=-2146233088    [d:\os\src\base\dms\common\FCFramework\ClusterUtils.cs::GetClusterNodesWhenClustered::2294]
01/07/2021-09:30:22.974 [Info] Successfully created firewall rule in destination proxy COB-FS-01.CityOfBuda.local to open required ports    [d:\os\src\base\dms\service\SmsUtil.cs::OpenDestinationProxySmbAndWmiPorts::2804]
01/07/2021-09:30:23.066 [Info] StartDeviceInventoryTask request job=UserFolderMigration    [d:\os\src\base\dms\service\StorageMigrationService.ITransfer.cs::StartDeviceInventoryTask::3275]
01/07/2021-09:30:23.066 [Info] StartTask taskId=3392d507-1e37-486f-a346-43393b0d9784 type=DeviceInventory    [d:\os\src\base\dms\service\OperationManager\SmsTaskManager.cs::StartTask::176]
01/07/2021-09:30:23.066 [Info] DeviceInventoryTask started device=COB-FS-01 taskId=3392d507-1e37-486f-a346-43393b0d9784    [d:\os\src\base\dms\service\OperationManager\DeviceInventoryTask.cs::Execute::57]
01/07/2021-09:30:23.066 [Info] DeviceInventoryTask using inventory proxy 95e9b91d-d6e0-4253-828a-f8e9ee778fad taskId=3392d507-1e37-486f-a346-43393b0d9784    [d:\os\src\base\dms\service\OperationManager\DeviceInventoryTask.cs::Execute::60]
01/07/2021-09:30:23.066 [Info] Device inventory started for device=COB-FS-01    [d:\os\src\base\dms\service\OperationManager\DeviceHelper.cs::InventoryDevice::173]
01/07/2021-09:30:24.656 [Erro] RequestInventoryDevice call succeeded but at least one of the stages failed. Relevant failed stage: DiskInfo. Error code: -2147024809    [d:\os\src\base\dms\service\OperationManager\DeviceHelper.cs::GetRelevantStageError::150]
01/07/2021-09:30:24.656 [Info] Device inventory ended for device=COB-FS-01 operationstate=Failed errorCode =-2147024809    [d:\os\src\base\dms\service\OperationManager\DeviceHelper.cs::InventoryDevice::292]
01/07/2021-09:30:24.656 [Info] DeviceInventoryTask completed device=COB-FS-01 taskId=3392d507-1e37-486f-a346-43393b0d9784 error=-2147024809 exception=     [d:\os\src\base\dms\service\OperationManager\DeviceInventoryTask.cs::Execute::83]
01/07/2021-09:30:26.112 [Info] CompleteDeviceInventoryTask request job=UserFolderMigration    [d:\os\src\base\dms\service\StorageMigrationService.ITransfer.cs::CompleteDeviceInventoryTask::3390]
01/07/2021-09:30:26.112 [Erro] GetTaskStatus request failed job=UserFolderMigration error=-2147024809: System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.StorageMigration.Service.DeviceInventoryTask.GetDevice()
   at Microsoft.StorageMigration.Service.StorageMigrationService.CompleteDeviceInventoryTask(String jobName, Guid taskId)    [d:\os\src\base\dms\service\StorageMigrationService.ITransfer.cs::CompleteDeviceInventoryTask::3433]
01/07/2021-09:30:36.142 [Erro] ExceptionMessage : (The socket transfer timed out after 00:00:10. You have exceeded the timeout set on your binding. The time allotted to this operation may have been a portion of a longer timeout.), ExceptionToString: (System.TimeoutException: The socket transfer timed out after 00:00:10. You have exceeded the timeout set on your binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.TimeoutException: The socket transfer timed out after 00:00:10. You have exceeded the timeout set on your binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
   at System.ServiceModel.Channels.SocketConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.NegotiateStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.ServiceModel.Channels.StreamConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.StreamConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.SessionConnectionReader.Receive(TimeSpan timeout)
   at System.ServiceModel.Channels.SynchronizedMessageSource.Receive(TimeSpan timeout)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EnsureInputClosed(TimeSpan timeout)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.OnClose(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Close(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnClose(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Close(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.MessageRpc.CloseChannel())    [d:\os\src\base\dms\service\ErrorHandlerBehaviorAttribute.cs::HandleError::37]
01/07/2021-09:30:36.142 [Erro] ExceptionMessage : (Value does not fall within the expected range.), ExceptionToString: (System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.StorageMigration.Service.DeviceInventoryTask.GetDevice()
   at Microsoft.StorageMigration.Service.StorageMigrationService.CompleteDeviceInventoryTask(String jobName, Guid taskId)
   at SyncInvokeCompleteDeviceInventoryTask(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet))    [d:\os\src\base\dms\service\ErrorHandlerBehaviorAttribute.cs::HandleError::37]

**Comment by illfated** [comment]
Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
