### ISSUE TITLE
Another issue that you can add to this page

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#6664]
For some reason, Test-SRTopology fails with a non-actoinable message.  Here is some output:

```powershell
PS C:\Foo> Get-SRPartnership

RunspaceId              : ad0c8beb-54fb-4f23-9253-3433a2e17b9a
DestinationComputerName : SRV2
DestinationRGName       : SRV2RG1
Id                      : 19e164bd-67f0-4b65-99ec-c7de97bb6731
SourceComputerName      : SRV1
SourceRGName            : SRV1RG1


PS C:\Foo> Test-SRTopology -SourceComputerName "SRV1" `
>>                 -SourceVolumeName "S:" `
>>                 -SourceLogVolumeName "G:" `
>>                 -DestinationComputerName "SRV2" `
>>                 -DestinationVolumeName "S:" `
>>                 -DestinationLogVolumeName "G:" `
>>                 -DurationInMinutes 10 `
>>                 -ResultPath "C:\Foo\" `
>>                 -IgnorePerfTests
WARNING: Specified cast is not valid.
WARNING: System.InvalidCastException
WARNING:    at Microsoft.FileServices.SR.Powershell.MSFTVolume.get_FileSystemType()
   at Microsoft.FileServices.SR.Powershell.Volume.GetVolume(String Path, String ComputerName)
   at Microsoft.FileServices.SR.Powershell.TestSRTopologyCommand.BeginProcessing()
Test-SRTopology: Specified cast is not valid.
```

I do not know how to resolve it - but the issue can be added to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad22e4dc-afd3-cf25-275b-dd8cebd38bca
* Version Independent ID: 18979d08-4b69-2f93-7fec-13793f5d56cf
* Content: [Known issues with Storage Replica](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/storage-replica-known-issues)
* Content Source: [WindowsServerDocs/storage/storage-replica/storage-replica-known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/storage-replica/storage-replica-known-issues.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
